name: Build

on:
  push:
    branches: ['main', 'development']
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Test and Build
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
